### ISSUE TITLE
starting service is not working

### ISSUE THREAD

**Issue by visenger** [cnvrg/imdb_deploy#3]
While trying to reproduce the example of the model deployment by running 
`kubectl apply -f deployment.yml` and looking into logs
`kubectl logs predict-imdb-7c9f7f8b74-kn9nr`
I realized the problem with the tensorflow:
```
[nltk_data]   Unzipping tokenizers/punkt.zip.
Traceback (most recent call last):
  File "server.py", line 3, in <module>
    import predict
  File "/imdb_keras/predict.py", line 12, in <module>
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'
```

**Comment by visenger** [comment]
Seems that the issue is related to the repository 
[imdb_keras](https://github.com/itayariel/imdb_keras), 
which is pointed in deployment.yaml

[PR](https://github.com/itayariel/imdb_keras/pulls) is pending
